"""
Fixtures for hazards testing.
"""

import os
import pkg_resources as pkg

la_url = ('ftp://tgftp.nws.noaa.gov/data/watches_warnings/thunderstorm/la/'
          'lac025.txt')

relpath = os.path.join('data', 'severe', '2015062121.severe')
severe_thunderstorm_file = pkg.resource_filename(__name__, relpath)

severe_print = r"""Headline: A SEVERE THUNDERSTORM WARNING REMAINS IN EFFECT UNTIL 530 PM EDT FOR NORTHEASTERN BEAVER AND SOUTH CENTRAL LAWRENCE COUNTIES
Product: Operational product
Action: Event continued
Office: KPBZ
Phenomena: Severe Thunderstorm
Significance: Warning
Event Tracking Number: 94
Beginning Time: None
Ending Time: 2015-06-21 21:30:00
Expiration Time: 2015-06-21 21:30:00
Well Known Text: POLYGON((80.43 40.84, 80.32 40.89, 80.16 40.83, 80.15 40.69, 80.43 40.84))"""

fflood_print = r"""Headline: None
Product: Operational product
Action: New event
Office: KIWX
Phenomena: Areal Flood
Significance: Warning
Event Tracking Number: 15
Beginning Time: 2015-06-27 13:07:00
Ending Time: 2015-06-27 16:00:00
Expiration Time: 2015-06-27 16:00:00
Well Known Text: None"""

fflood_txt = r"""THE NATIONAL WEATHER SERVICE IN NORTHERN INDIANA  HAS ISSUED A

* FLOOD WARNING FOR...
  DE KALB COUNTY IN NORTHEASTERN INDIANA...
  NORTHEASTERN NOBLE COUNTY IN NORTHEASTERN INDIANA...
  LAGRANGE COUNTY IN NORTHEASTERN INDIANA...
  STEUBEN COUNTY IN NORTHEASTERN INDIANA...
  BRANCH COUNTY IN SOUTHWESTERN MICHIGAN...
  HILLSDALE COUNTY IN SOUTHEASTERN MICHIGAN...
  ST. JOSEPH COUNTY IN SOUTHWESTERN MICHIGAN...
  PAULDING COUNTY IN WEST CENTRAL OHIO...
  VAN WERT COUNTY IN WEST CENTRAL OHIO...
  WILLIAMS COUNTY IN NORTHWESTERN OHIO...
  WEST CENTRAL FULTON COUNTY IN NORTHWESTERN OHIO...
  DEFIANCE COUNTY IN NORTHWESTERN OHIO...

* UNTIL NOON EDT

* AT 906 AM EDT...DOPPLER RADAR AND AUTOMATED RAIN GAUGES INDICATED
  THAT HEAVY RAIN WAS FALLING OVER THE AREA. THAT HEAVY RAIN WILL
  CAUSE FLOODING. UP TO TWO INCHES OF RAIN HAVE ALREADY FALLEN.

* SOME LOCATIONS THAT WILL EXPERIENCE FLOODING INCLUDE...
  DEFIANCE...AUBURN...STURGIS...COLDWATER...VAN WERT...
  KENDALLVILLE...ANGOLA...BRYAN...HILLSDALE...THREE RIVERS...
  GARRETT...MONTPELIER...HICKSVILLE...BUTLER...LAGRANGE...PAULDING...
  AVILLA...BRONSON...ALBION AND JONESVILLE.

PRECAUTIONARY/PREPAREDNESS ACTIONS...

MOST FLOOD DEATHS OCCUR IN AUTOMOBILES. NEVER DRIVE YOUR VEHICLE INTO
AREAS WHERE THE WATER COVERS THE ROADWAY. FLOOD WATERS ARE USUALLY
DEEPER THAN THEY APPEAR. JUST ONE FOOT OF FLOWING WATER IS POWERFUL
ENOUGH TO SWEEP VEHICLES OFF THE ROAD. WHEN ENCOUNTERING FLOODED
ROADS MAKE THE SMART CHOICE...TURN AROUND...DONT DROWN.

EXCESSIVE RUNOFF FROM HEAVY RAINFALL WILL CAUSE FLOODING OF SMALL
CREEKS AND STREAMS...HIGHWAYS AND UNDERPASSES IN URBAN AREAS.
ADDITIONALLY...COUNTRY ROADS AND FARMLANDS ALONG THE BANKS OF
CREEKS...STREAMS AND OTHER LOW LYING AREAS ARE SUBJECT TO FLOODING."""

# Example of summary with a single quote character.
relpath = os.path.join('data', 'severe', '2015062722.severe')
summary_with_quote = pkg.resource_filename(__name__, relpath)
